services:

  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - backend

  backend:
    build: ./backend
    volumes:
      - backend_cache:/app/cache
    environment:
      - APP_ENVIRONMENT=production
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
  
  ollama:
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  backend_cache:
  ollama:
